# Generated by Django 3.2.18 on 2023-04-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageName', models.CharField(max_length=256)),
                ('initialData', models.TextField(max_length=99999999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=9999999)),
                ('errors', models.IntegerField(default=0)),
                ('totalRepeatedTimes', models.IntegerField(default=0)),
                ('repeatIndex', models.IntegerField(default=0)),
                ('repeatDate', models.DateField(null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='words.wordstorage')),
            ],
        ),
    ]
