# Generated by Django 3.2.18 on 2023-05-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_wordstorage_ignore2ndstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordstorage',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
