# Generated by Django 3.2.18 on 2023-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pronounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
                ('repeatsCount', models.IntegerField()),
                ('errorsCount', models.IntegerField()),
                ('repeatDate', models.DateField()),
            ],
        ),
    ]
