# Generated by Django 3.2.18 on 2023-04-30 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronounce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='pronounce',
            name='errorsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pronounce',
            name='repeatDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pronounce',
            name='repeatsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pronounce',
            name='hint',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='pronounce.hint'),
        ),
    ]
