# Generated by Django 3.2.18 on 2023-04-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronounce', '0002_auto_20230430_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
