# Generated by Django 3.2.18 on 2023-03-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('short_name', models.CharField(max_length=256, unique=True)),
                ('task_intervals', models.CharField(default='', max_length=256)),
                ('avg_cost', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('priority', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=256, unique=True)),
                ('task_cost', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('task_repeat_in_index', models.IntegerField(default=0)),
                ('task_repeat_date', models.DateField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='math_gachi_train.collectionmodel')),
            ],
        ),
    ]
