# Generated by Django 3.2.18 on 2023-03-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_gachi_train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
