# Generated by Django 3.2.18 on 2023-03-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_gachi_train', '0004_collectionmodel_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('weekDays', models.CharField(max_length=999)),
            ],
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='math_gachi_train.subject'),
        ),
    ]
